#!/usr/bin/env node
/**
 * generate.mjs — profile → fluid-tokens.css
 *
 * Uses utopia-core when it is installed, and falls back to the same
 * calculation inline when it isn't, so the repo works with zero install.
 * Either way the output is byte-identical: the fallback is the published
 * Utopia formula, and test/idempotence.mjs proves it reproduces a
 * hand-verified token file exactly.
 *
 * Usage:
 *   node scripts/generate.mjs --profile <profile.json> [--out <file.css>]
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

let core = null;
try {
  core = await import('utopia-core');
} catch {
  /* fallback below */
}

/** Trim trailing zeros without going scientific. */
const fmt = (n) => {
  const s = n.toFixed(4).replace(/0+$/, '').replace(/\.$/, '');
  return s === '-0' ? '0' : s;
};

/**
 * The Utopia clamp. Given a size pair across a viewport pair:
 *   slope = (maxSize - minSize) / (maxWidth - minWidth)
 *   base  = minSize - slope * minWidth
 *   clamp(minRem, baseRem + slopeVw, maxRem)
 */
function clampFor(minSize, maxSize, minWidth, maxWidth, root) {
  if (minSize === maxSize) return `${fmt(minSize / root)}rem`;
  const slope = (maxSize - minSize) / (maxWidth - minWidth);
  const base = minSize - slope * minWidth;
  const lo = Math.min(minSize, maxSize) / root;
  const hi = Math.max(minSize, maxSize) / root;
  return `clamp(${fmt(lo)}rem, ${fmt(base / root)}rem + ${fmt(slope * 100)}vw, ${fmt(hi)}rem)`;
}

function buildClamp(minSize, maxSize, minWidth, maxWidth, root) {
  if (core?.calculateClamp && minSize !== maxSize) {
    return core.calculateClamp({
      minSize,
      maxSize,
      minWidth,
      maxWidth,
      relativeTo: 'viewport',
      usePx: false,
    });
  }
  return clampFor(minSize, maxSize, minWidth, maxWidth, root);
}

function parseArgs(argv) {
  const args = { profile: null, out: null };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--profile') args.profile = argv[++i];
    else if (argv[i] === '--out') args.out = argv[++i];
  }
  return args;
}

const pad = (s, n) => String(s).padEnd(n);

function main() {
  const args = parseArgs(process.argv.slice(2));
  const profilePath = args.profile
    ? resolve(args.profile)
    : join(__dirname, '..', 'profiles', 'default.json');
  const p = JSON.parse(readFileSync(profilePath, 'utf8'));

  const root = p.rootFontSize ?? 16;
  const { min: minW, max: maxW } = p.anchors;
  const L = [];

  L.push('/* ==========================================================================');
  L.push(`   Fluid Tokens — ${p.name}`);
  L.push('   Method: Utopia (https://utopia.fyi) — fluid type + space via clamp()');
  L.push(`   Anchors: ${minW}px (mobile) → ${maxW}px (desktop). Root font size assumed ${root}px.`);
  L.push('');
  L.push('   GENERATED by fluid-responsive-designs. Edit the profile, not this file.');
  L.push(`   Profile: ${p.id}`);
  L.push('');
  L.push('   Formula used for every token:');
  L.push(`     slope_vw = (max_px - min_px) / (${maxW} - ${minW}) * 100`);
  L.push(`     base_rem = (min_px - slope * ${minW}) / ${root}`);
  L.push('     value    = clamp(min_rem, base_rem + slope_vw, max_rem)');
  L.push('   ========================================================================== */');
  L.push('');
  L.push(':root {');

  // ---- type ---------------------------------------------------------------
  const typeScale = p.type?.scale ?? {};
  if (Object.keys(typeScale).length) {
    L.push('  /* ---------------------------------------------------------------------');
    L.push('     TYPE — each role scales only WITHIN its mandated band. clamp() bounds');
    L.push(`     both ends, so nothing renders below ${p.type.globalBounds?.min}px or above ${p.type.globalBounds?.max}px at ANY width.`);
    L.push('     --------------------------------------------------------------------- */');
    L.push('');
    for (const [name, spec] of Object.entries(typeScale)) {
      const [lo, hi] = spec.pair;
      L.push(`  /* ${name.replace('--font-', '')} — ${lo}px → ${hi}px | ${spec.use} */`);
      L.push(`  ${name}: ${buildClamp(lo, hi, minW, maxW, root)};`);
    }
    L.push('');
  }

  const leading = p.type?.leading ?? {};
  if (Object.keys(leading).length) {
    L.push('  /* Line height — UNITLESS so it scales with the fluid font size for free.');
    L.push('     Never set a px line-height on fluid text: it desynchronises and clips');
    L.push('     descenders at one end of the range. */');
    for (const [k, v] of Object.entries(leading)) L.push(`  ${k}: ${v};`);
    L.push('');
  }

  const tracking = p.type?.tracking ?? {};
  if (Object.keys(tracking).length) {
    L.push('  /* Letter spacing — em only, so optical tightening tracks the fluid size. */');
    for (const [k, v] of Object.entries(tracking)) L.push(`  ${k}: ${v};`);
    L.push('');
  }

  // ---- space --------------------------------------------------------------
  const spaceScale = p.space?.scale ?? {};
  if (Object.keys(spaceScale).length) {
    L.push('  /* ---------------------------------------------------------------------');
    L.push(`     SPACE — t-shirt ladder. Both endpoints land on the ${p.space.gridPt}pt grid.`);
    L.push('     Off-grid intermediates between the anchors are expected and correct:');
    L.push('     the grid is a design-decision constraint, not a runtime one.');
    L.push('     --------------------------------------------------------------------- */');
    L.push('');
    for (const [name, spec] of Object.entries(spaceScale)) {
      const [lo, hi] = spec.pair;
      const note = `/* ${String(lo).padStart(2)} → ${String(hi).padStart(2)} */`;
      L.push(`  ${pad(name + ':', 22)} ${pad(buildClamp(lo, hi, minW, maxW, root) + ';', 48)} ${note}`);
    }
    L.push('');
  }

  const semantic = p.space?.semantic ?? {};
  if (Object.keys(semantic).length) {
    L.push('  /* ---------------------------------------------------------------------');
    L.push('     SEMANTIC SPACE — use these in components, not the raw ladder, so the');
    L.push('     intent stays legible at the call site.');
    L.push('     --------------------------------------------------------------------- */');
    L.push('');
    for (const [name, spec] of Object.entries(semantic)) {
      const [lo, hi] = spaceScale[spec.ref]?.pair ?? ['?', '?'];
      L.push(`  ${pad(name + ':', 26)} ${pad(`var(${spec.ref});`, 22)} /* ${lo} → ${hi}  ${spec.use} */`);
    }
    L.push('');
  }

  // ---- static floors ------------------------------------------------------
  const btn = p.static?.buttonPadding;
  if (btn) {
    L.push('  /* Button padding — STATIC. Buttons are hit targets before they are');
    L.push(`     layout; fluid padding fights the ${p.static.tapTargetMin}px tap-target floor. */`);
    for (const [size, v] of Object.entries(btn)) {
      L.push(
        `  ${pad(`--pad-btn-${size}-block:`, 24)} ${pad(fmt(v.block / root) + 'rem;', 10)} ${pad(`--pad-btn-${size}-inline:`, 25)} ${pad(fmt(v.inline / root) + 'rem;', 10)} /* ${v.block} / ${v.inline} */`
      );
    }
    L.push('');
  }

  // ---- grid ---------------------------------------------------------------
  const steps = p.structural?.columnSteps ?? [];
  if (steps.length) {
    L.push('  /* ---------------------------------------------------------------------');
    L.push('     GRID — gutter is fluid (scalar); COLUMN COUNT IS NOT (structural).');
    L.push('     Column count is the one value that legitimately steps.');
    L.push('     --------------------------------------------------------------------- */');
    L.push('');
    if (p.structural.gutterRef) L.push(`  --grid-gutter: var(${p.structural.gutterRef});`);
    L.push(`  --grid-columns: ${steps[0].columns};`);
    L.push('');
  }

  // ---- a11y floors --------------------------------------------------------
  const s = p.static ?? {};
  L.push('  /* ---------------------------------------------------------------------');
  L.push('     ACCESSIBILITY FLOORS — never fluid, never clamped down. A target that');
  L.push('     reads 44px at the top anchor is under 44px at every width below it.');
  L.push('     --------------------------------------------------------------------- */');
  L.push('');
  L.push(`  --tap-target-min: ${s.tapTargetMin}px;      /* mobile — WCAG 2.5.5 + Apple HIG */`);
  L.push(`  --click-target-min: ${s.clickTargetMin}px;    /* desktop pointer */`);
  L.push(`  --interactive-gap-min: ${s.interactiveGapMin}px;  /* minimum gap between interactive elements */`);
  L.push(`  --focus-ring-width: ${s.focusRingWidth}px;     /* static — a fluid focus ring is a bug */`);
  L.push(`  --focus-ring-offset: ${s.focusRingOffset}px;`);
  L.push('}');
  L.push('');

  // ---- structural queries -------------------------------------------------
  if (steps.length > 1) {
    L.push('/* Column count is the only thing that still needs breakpoints. */');
    for (const st of steps.slice(1)) {
      L.push(`@media (min-width: ${st.minWidth}px)  { :root { --grid-columns: ${st.columns};  } }`);
    }
    L.push('');
  }

  const css = L.join('\n');
  if (args.out) {
    writeFileSync(resolve(args.out), css, 'utf8');
    console.error(`wrote ${args.out} (${core ? 'utopia-core' : 'built-in maths'})`);
  } else {
    process.stdout.write(css);
  }
}

main();
